const PLAYERLENGTH = 8;
const PLAYERBOTTOMDISTANCE = 7;
const MUOVIDX = 10;
const MUOVISX = 10;
const MURODX = 65; //vw
const MUROSX = 35; // vw
const MUROTOP = 40; // vw
const PLAYERHEIGHT = 1;
const PLAYGROUNDWIDTH = 30;
const PLAYGROUNDHEIGHT = 35;
const MUROBOTTOM = 0;
const BALLWIDTH = 0.8;
const BLOCKWIDTH = 3;
const BLOCKHEIGHT = 2;
const SCARTOINLATERALE = 0.2;
const SCARTOOUT = 1;
const SCARTOINBASE = 0.3
const SCARTO = 0.2;
const POWERUPWIDTH = 2;
const clockTime = 15;
const ballSpeed = 0.5;
